### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/developer-docs#12]
FILE: ./ospsuite-r-setup/Setup-ospsuite-R-on-Ubuntu.md
[✖] https://aka.ms/dotnet-download → Status: 0 Error: ESOCKETTIMEDOUT

FILE: ./setup/getting_started.md
[✖] https://www.microsoft.com/en-ca/download/details.aspx?id=15697 → Status: 0 Error: ESOCKETTIMEDOUT

**Comment by georgeDaskalakis** [comment]
not sure why this remained open, although the PR linked to it was merged. In any case, it has been resolved. I am closing.
